<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-9STP60L" failures="1" tests="3" name="testPolicyBazzar.POL_TC_1234_ValidatingPersonalDetails" time="3.076" errors="0" timestamp="2023-07-01T10:17:31 IST" skipped="0">
  <testcase classname="testPolicyBazzar.POL_TC_1234_ValidatingPersonalDetails" name="validatingProfilePageURL" time="2.527">
    <failure message="TC is failed expected [ttps://myaccount.policybazaar.com/profile] but found [https://myaccount.policybazaar.com/profile]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: TC is failed expected [ttps://myaccount.policybazaar.com/profile] but found [https://myaccount.policybazaar.com/profile]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testPolicyBazzar.POL_TC_1234_ValidatingPersonalDetails.validatingProfilePageURL(POL_TC_1234_ValidatingPersonalDetails.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[validatingProfilePageURL Execution started
Taking screenshot and stored at-C:\Users\palla\OneDrive\Documents\Automation\Screenshot\PolicyBazzar\validatingProfilePageURL-W2.png
validatingProfilePageURL is failed, Please check and try again]]>
    </system-out>
  </testcase> <!-- validatingProfilePageURL -->
  <testcase classname="testPolicyBazzar.POL_TC_1234_ValidatingPersonalDetails" name="validatingUserName" time="0.401">
    <system-out>
      <![CDATA[validatingUserName Execution started
Reading data from excel row number-1, cell number-2
Actual and expected username are matching - TC is Passed
Taking screenshot and stored at-C:\Users\palla\OneDrive\Documents\Automation\Screenshot\PolicyBazzar\Pallavi Pustake-POL_TC_1234-m0.png
validatingUserName is successfully executed]]>
    </system-out>
  </testcase> <!-- validatingUserName -->
  <testcase classname="testPolicyBazzar.POL_TC_1234_ValidatingPersonalDetails" name="validatingEmailID" time="0.148">
    <system-out>
      <![CDATA[validatingEmailID Execution started
Reading data from excel row number-1, cell number-3
Actual and expected EmailID's are matching - TC is passed
validatingEmailID is successfully executed]]>
    </system-out>
  </testcase> <!-- validatingEmailID -->
  <system-out>
    <![CDATA[Launching Policy Bazzar Appilcation
Waiting for complete load page, wait time-1000
Clicking on sign in home page
Waiting for complete load page, wait time-1000
Reading data from excel row number-1, cell number-0
Entering mobile number
Waiting for,wait time-1000
Clicking on sign in with password
Waiting for,wait time-1000
Reading data from excel row number-1, cell number-1
Entering password
Clicking on sign in
Waiting for complete load page, wait time-1500
Clicking on my account
Waiting for,wait time-1000
Clicking on my profile
Waiting for complete load page, wait time-1500
validatingProfilePageURL Execution started
Taking screenshot and stored at-C:\Users\palla\OneDrive\Documents\Automation\Screenshot\PolicyBazzar\validatingProfilePageURL-W2.png
validatingProfilePageURL is failed, Please check and try again
validatingUserName Execution started
Reading data from excel row number-1, cell number-2
Actual and expected username are matching - TC is Passed
Taking screenshot and stored at-C:\Users\palla\OneDrive\Documents\Automation\Screenshot\PolicyBazzar\Pallavi Pustake-POL_TC_1234-m0.png
validatingUserName is successfully executed
validatingEmailID Execution started
Reading data from excel row number-1, cell number-3
Actual and expected EmailID's are matching - TC is passed
validatingEmailID is successfully executed
Logging out from Policy Bazzar Application]]>
  </system-out>
</testsuite> <!-- testPolicyBazzar.POL_TC_1234_ValidatingPersonalDetails -->
